name: 'Build application'

on: [ push ]

jobs:
  build:
    name: 'Building'

    strategy:
      matrix:
        system:
          - windows-latest
          - ubuntu-latest
        config:
          - Debug
          - Release

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build WebApplication1.sln -p:Configuration=${{ matrix.config }} --no-restore

      - name: Run tests
        run: dotnet test WebApplication1.sln --no-restore
